>Take a first look at the data

In [2]:
import pandas as pd
import numpy as np 

flights_data= pd.read_csv(r"C:\Users\musta\Downloads\2008.csv")

# set seed for reproducibility
np.random.seed(0)

In [3]:
flights_data.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,926.0,930,1054.0,1100,WN,1746,...,3.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,...,3.0,10.0,0,NaN,0,2.0,0.0,0.0,0.0,32.0

>We can see some NaN values.

In [4]:
missing_values_count= flights_data.isnull().sum() # -> With this code, we can see how many NaN values there are in each row.

missing_values_count[0:10] # -> To find the NaN values in the first ten columns, this line of code can be used.

Year                  0
Month                 0
DayofMonth            0
DayOfWeek             0
DepTime          136246
CRSDepTime            0
ArrTime          151649
CRSArrTime            0
UniqueCarrier         0
FlightNum             0
dtype: int64

In [5]:
#   First, we need to find the total number of missing values.
total_cells =  np.prod(flights_data.shape)
total_missing = missing_values_count.sum()

In [6]:
#   Now we need to find out what percentage of the data is missing.

percent_missing= (total_missing/ total_cells)*100 
print(f"The missing data is equal to {percent_missing} of all data.")

The missing data is equal to 17.49215051445353 of all data.

>The most fundamental question we can use to determine why a value is missing is:

>“Is this value missing because it wasn't recorded or because it doesn't exist?”

>If a value is missing because it doesn't exist, it doesn't make sense to try to guess what that value might be. You'll probably want to keep these values as NaN.

>On the other hand, if a value is missing because it was not recorded, you can try to estimate what it might be based on other values in that column and row. This is called imputation.

In [7]:
# look at the number of missing points in the first fifteen columns
missing_values_count[0:15]

Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime              136246
CRSDepTime                0
ArrTime              151649
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum               83365
ActualElapsedTime    154699
CRSElapsedTime          844
AirTime              154699
ArrDelay             154699
dtype: int64

>Drop missing values

In [8]:
# remove all the rows that contain a missing value
flights_data.dropna()

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, DepTime, CRSDepTime, ArrTime, CRSArrTime, UniqueCarrier, FlightNum, TailNum, ActualElapsedTime, CRSElapsedTime, AirTime, ArrDelay, DepDelay, Origin, Dest, Distance, TaxiIn, TaxiOut, Cancelled, CancellationCode, Diverted, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay]
Index: []

[0 rows x 29 columns]

>All our data appears to be missing. The reason is simple: every row contains at least one missing value.

In [9]:
#    To fix this, it makes more sense to delete all columns containing at least one missing value rather than every row containing at least one missing value.

columns_with_na_dropped= flights_data.dropna(axis=1)
columns_with_na_dropped.head()

,Year,Month,DayofMonth,DayOfWeek,CRSDepTime,CRSArrTime,UniqueCarrier,FlightNum,Origin,Dest,Distance,Cancelled,Diverted
0,2008,1,3,4,1955,2225,WN,335,IAD,TPA,810,0,0
1,2008,1,3,4,735,1000,WN,3231,IAD,TPA,810,0,0
2,2008,1,3,4,620,750,WN,448,IND,BWI,515,0,0
3,2008,1,3,4,930,1100,WN,1746,IND,BWI,515,0,0
4,2008,1,3,4,1755,1925,WN,3920,IND,BWI,515,0,0

In [10]:
# just how much data did we lose?
print("Columns in original dataset: %d \n" % flights_data.shape[1])
print("Columns with na's dropped: %d" % columns_with_na_dropped.shape[1])

Columns in original dataset: 29

Columns with na's dropped: 13

>It appears that we have missing values in 16 columns.

>Filling in missing values automatically

In [11]:
flights_data.columns

Index(['Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime',
       'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum',
       'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

In [12]:
#   get a small subset of the Flights dataset

subset_flights = flights_data.loc[:, [
    'DepDelay',       # numeric
    'ArrDelay',       # numeric
    'AirTime',        # numeric
    'TaxiIn',         # numeric
    'Year',           # categorical-like
    'Cancelled',      # logical
    'CancellationCode' # categorical
]]


subset_flights.head()

   DepDelay  ArrDelay  AirTime  TaxiIn  Year  Cancelled CancellationCode
0       8.0     -14.0    116.0     4.0  2008          0              NaN
1      19.0       2.0    113.0     5.0  2008          0              NaN
2       8.0      14.0     76.0     3.0  2008          0              NaN
3      -4.0      -6.0     78.0     3.0  2008          0              NaN
4      34.0      34.0     77.0     3.0  2008          0              NaN

In [13]:
#   replace all NA's with 0

subset_flights.fillna(0)

         DepDelay  ArrDelay  AirTime  TaxiIn  Year  Cancelled CancellationCode
0             8.0     -14.0    116.0     4.0  2008          0                0
1            19.0       2.0    113.0     5.0  2008          0                0
2             8.0      14.0     76.0     3.0  2008          0                0
3            -4.0      -6.0     78.0     3.0  2008          0                0
4            34.0      34.0     77.0     3.0  2008          0                0
...           ...       ...      ...     ...   ...        ...              ...
7009723       3.0      14.0     71.0     6.0  2008          0                0
7009724      -1.0      -2.0    139.0     5.0  2008          0                0
7009725      -5.0       0.0     85.0    24.0  2008          0                0
7009726      11.0       9.0     89.0    13.0  2008          0                0
7009727       7.0      -5.0    104.0     8.0  2008          0                0

[7009728 rows x 7 columns]

>Another method is to replace missing values with the value in the next column.
(This may be useful in data where the observations have a logical sequence)

In [14]:
#   replace all NA's the value that comes directly after it in the same column, 
#   then replace all the remaining na's with 0


subset_flights.fillna(method='bfill', axis=0).fillna(0)

C:\Users\musta\AppData\Local\Temp\ipykernel_22696\4216645902.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  subset_flights.fillna(method='bfill', axis=0).fillna(0)

         DepDelay  ArrDelay  AirTime  TaxiIn  Year  Cancelled CancellationCode
0             8.0     -14.0    116.0     4.0  2008          0                A
1            19.0       2.0    113.0     5.0  2008          0                A
2             8.0      14.0     76.0     3.0  2008          0                A
3            -4.0      -6.0     78.0     3.0  2008          0                A
4            34.0      34.0     77.0     3.0  2008          0                A
...           ...       ...      ...     ...   ...        ...              ...
7009723       3.0      14.0     71.0     6.0  2008          0                0
7009724      -1.0      -2.0    139.0     5.0  2008          0                0
7009725      -5.0       0.0     85.0    24.0  2008          0                0
7009726      11.0       9.0     89.0    13.0  2008          0                0
7009727       7.0      -5.0    104.0     8.0  2008          0                0

[7009728 rows x 7 columns]